spring:
  redis:
    host: localhost
#    password:
    port: 6379
    database: 2
#企业微信注册地址https://work.weixin.qq.com/wework_admin/register_wx?from=myhome
#注册完进入后台 --> 应用管理-自建-创建应用 --> 进入自建应用获取 AgentId Secret （编辑可见人员） --> 我的企业-企业信息 获取企业ID --> 我的企业-微信插件 微信扫一扫加入企业 --> api 推送消息
#企业微信发送应用消息接口文档地址： https://work.weixin.qq.com/api/doc/90000/90135/90236



wxpush:
  #  企业id
  corpid: 填写你的企业id
  #  企业应用的id
  agentid: 企业应用的id
    #  应用的凭证密钥
  corpsecret: 应用的凭证密钥

ql:
  baseUrl: ip:端口
  #  baseUrl: 1.14.252.104:7501
  clientId: 青龙应用client
  clientSecret: 青龙应用clientSecret
  logFilePath: /ql2/log/KingRan_KR_jd_jddj_fruit
